enum AppCopy {
    static let appName = "黑码码"
    static let appNameWithTechnicalName = "黑码码（VibeBlank）"
    static let statusTooltip = "黑码码视觉隐私保护"
    static let overlayWindowTitle = "黑码码遮罩"
    static let settingsWindowTitle = "黑码码设置"
    static let residentUtilityReason = "黑码码是常驻菜单栏工具。"

    enum Menu {
        static let activate = "开启黑屏"
        static let deactivate = "退出黑屏"
        static let scopePrefix = "覆盖范围"
        static let primaryTriggerAvailable = "主触发：Command 三连"
        static let primaryTriggerNeedsPermission = "主触发：Command 三连需要辅助功能权限"
        static let primaryTriggerOff = "主触发：已关闭"
        static let comboHotkeyOff = "组合键：已关闭"
        static let comboHotkeyUnavailable = "组合键：不可用（请重新录制）"
        static func comboHotkeyAvailable(_ displayName: String) -> String {
            "组合键：\(displayName)"
        }
        static let cornerOff = "触发角：已关闭"
        static func cornerAvailable(_ displayName: String) -> String {
            "触发角：\(displayName)"
        }
        static let settings = "设置..."
        static let quit = "退出黑码码"
    }

    enum Settings {
        static let overlaySection = "遮罩"
        static let overlaySectionDescription = "控制黑屏覆盖范围和黑屏时显示的内容。"
        static let coverPicker = "覆盖范围"
        static let coverPickerDetail = "默认只覆盖外接显示器，内置屏保持可用。"
        static let backgroundStylePicker = "背景样式"
        static let backgroundStylePickerDetail = "纯黑最安静，毛玻璃让遮罩更有空间感。"
        static let contentPicker = "显示内容"
        static let contentPickerDetail = "纯黑最安静，也可以显示时间、状态文字或粒子计时。"
        static let timerPlacementPicker = "计时器位置"
        static let timerPlacementPickerDetail = "粒子计时显示在角落，默认右下角。"
        static let customTextPlaceholder = "自定义文字"
        static let exitSection = "退出方式"
        static let exitSectionDescription = "Esc 始终可退出，其他退出方式按场景开启。"
        static let clickToExit = "点击遮罩退出"
        static let clickToExitDetail = "适合只遮外接屏、回来后用鼠标快速恢复。"
        static let keyToExit = "按任意键退出"
        static let keyToExitDetail = "按键会被遮罩消费，不会传给底层应用。"
        static let escapeHint = "Esc 始终可退出黑屏，作为安全兜底。"
        static let triggersSection = "触发方式"
        static let triggersSectionDescription = "选择最顺手的开启方式，并保留菜单栏兜底。"
        static let launchAtLogin = "登录时自动启动黑码码"
        static let launchAtLoginDetail = "重启后保持菜单栏与触发器常驻。"
        static let hotCorner = "触发角开启黑屏"
        static let hotCornerDetail = "鼠标进入指定角落后开启黑屏，只开启不退出。"
        static let hotCornerPicker = "角落"
        static let enableModifierTap = "启用 Command 三连"
        static let enableModifierTapDetail = "默认任意 Command 连按三次即可切换黑屏。"
        static let commandSidePicker = "Command 按键"
        static let openAccessibilitySettings = "打开辅助功能设置"
        static let enableComboHotkey = "启用组合键"
        static let enableComboHotkeyDetail = "为传统快捷键工作流保留，可录制并检测冲突。"
        static let recordComboHotkey = "录制组合键"
        static let cancelRecording = "取消"
        static let recordingHint = "请按下新的组合键，例如 Control + Option + Command + B。"
        static let comboNeedsModifier = "组合键至少需要一个修饰键。"
        static let comboConflict = "这个组合键不可用，可能已被系统或其他应用占用。"
        static let triggersHint = "菜单栏和 Esc 始终可用。触发角只开启黑屏，键盘触发可开启或退出。"
        static let headline = "黑码码"
        static let subtitle = "让 AI 悄悄帮你干活。"
        static let safetyNotice = "黑码码是视觉隐私辅助工具，不是锁屏或身份验证工具。"
        static let restoreDefaults = "恢复默认设置"
        static let defaultsHint = "默认：登录启动，Command 三连，仅外接显示器。"
    }
}
